bind_address		= "0.0.0.0"		# Address to listen on
bind_port		= 8080			# Port to listen on
server_name		= "telos.local"		# Domain to use in URLs
storage_path		= "public"		# Path to storage directory
max_request_size	= 1073741824		# Roughly max file size (1 GiB)
